### ISSUE TITLE
Introduce alternative test frameworks

### ISSUE THREAD

**Issue by furzeface** [furzeface/js-tdd-skeleton#2]
In branches, so I can switch between types of project setup.
- Karma
- Jasmine

**Comment by furzeface** [comment]
Yeah I know Karma is a runner I just cba to words 😄

**Comment by furzeface** [comment]
Yep Tape - good idea @tawashley - want to have a go at PRing it?

I'm just trying to get a few different ones in here so I can clone this into a project, switch branch and have whichever set up I want, so the more the better 😃 

 :octocat:

**Comment by tawashley** [comment]
That idea about having a branch per test framework is gold! Yeah, I'll have a look :) - where would it be pulled into though?

**Comment by furzeface** [comment]
Create a new branch, call it `feature/FRAMEWORK` I think 😄  feel free to add and delete whatever.

The branch will be sort of like its own mini repo, I'm abusing branching here a bit but if it works for me.. :octocat:
